return function(colors, theme)
  return {
    ["@variable"] = { fg = theme.base05 },
    ["@variable.builtin"] = { fg = theme.base09 },
    ["@variable.parameter"] = { fg = theme.base08 },
    ["@variable.member"] = { fg = theme.base08 },
    ["@variable.member.key"] = { fg = theme.base08 },
    ["@module"] = { fg = theme.base08 },

    ["@constant"] = { fg = theme.base09 },
    ["@constant.builtin"] = { fg = theme.base09 },
    ["@constant.macro"] = { fg = theme.base08 },

    ["@string"] = { fg = theme.base0B },
    ["@string.regex"] = { fg = theme.base0C },
    ["@string.escape"] = { fg = theme.base0C },
    ["@character"] = { fg = theme.base08 },
    ["@number"] = { fg = theme.base09 },
    ["@number.float"] = { fg = theme.base09 },

    ["@annotation"] = { fg = theme.base0F },
    ["@attribute"] = { fg = theme.base0A },
    ["@error"] = { fg = theme.base08 },

    ["@keyword"] = { fg = theme.base0E },
    ["@keyword.function"] = { fg = theme.base0E },
    ["@keyword.return"] = { fg = theme.base0E },
    ["@keyword.operator"] = { fg = theme.base0E },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.conditional"] = { fg = theme.base0E },
    ["@keyword.conditional.ternary"] = { fg = theme.base0E },
    ["@keyword.repeat"] = { fg = theme.base0A },
    ["@keyword.storage"] = { fg = theme.base0A },
    ["@keyword.directive.define"] = { fg = theme.base0E },
    ["@keyword.directive"] = { fg = theme.base0A },
    ["@keyword.exception"] = { fg = theme.base08 },

    ["@function"] = { fg = theme.base0D },
    ["@function.builtin"] = { fg = theme.base0D },
    ["@function.macro"] = { fg = theme.base08 },
    ["@function.call"] = { fg = theme.base0D },
    ["@function.method"] = { fg = theme.base0D },
    ["@function.method.call"] = { fg = theme.base0D },
    ["@constructor"] = { fg = theme.base0C },

    ["@operator"] = { fg = theme.base05 },
    ["@reference"] = { fg = theme.base05 },
    ["@punctuation.bracket"] = { fg = theme.base0F },
    ["@punctuation.delimiter"] = { fg = theme.base0F },
    ["@symbol"] = { fg = theme.base0B },
    ["@tag"] = { fg = theme.base0A },
    ["@tag.attribute"] = { fg = theme.base08 },
    ["@tag.delimiter"] = { fg = theme.base0F },
    ["@type.builtin"] = { fg = theme.base0A },
    ["@property"] = { fg = theme.base08 },

    ["@comment"] = { fg = colors.grey_fg },
    ["@comment.todo"] = { fg = colors.grey, bg = colors.white },
    ["@comment.warning"] = { fg = colors.black2, bg = theme.base09 },
    ["@comment.note"] = { fg = colors.black, bg = colors.blue },
    ["@comment.danger"] = { fg = colors.black2, bg = colors.red },

    ["@diff.plus"] = { fg = colors.green },
    ["@diff.minus"] = { fg = colors.red },
    ["@diff.delta"] = { fg = colors.light_grey },
  }
end
